apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCEXGgwmizXEEu6MKpLHzh9Bn9AA0IGLkgI9DBkvmh0BqUU7pS2wP9ciNl3ZtodMif0AF86zXqhRjqli2PxFlYQmWJ3uDPqmDd/egH4LDvgIbVm3eTW4P0YdynLPy2IpfBHWs+ySR7bJNorHdwN79AtGEfFutNGyPR0m0Bb7+l4nUpnSe3yg/27Cyx3ds+UzBFjKePBmNv43DhJqeQ/f386vhwSRER9CHEa8nF0FJmWKBp3AvJwl1K2gWU7W3kKbCI1pzHCOHBxZ22Rtc3ZPZr2MSPhUdgcZLdds1K6hJQ/v9eNZBlhMWbLgZk20bAktEYWDQbXRzwibc2DRSbFY805B3ijPPFt9lKx+FQW5dojHUqcV6mnRILvufrmIEQBknSWVB6IM8uKFqIMrh7Mt4gbldkf2K6/4mZtQtY4jTKknJrNwlNiZTabq8tInAI+WFS+8hIc6yDq5vsgmab/NlyGPXTOsf1zB3WwWbZnoidfLCuczhtTrqykLGKWOLCCwAg68TZJuIE8UaURlzj4KocCUx4bsWy2DG0qaNTmQ8AAg/njNQcq2gKDkuTa1gn76qQ8mao3Oc8xiOLhhnEilg2ZjwUAb8WDs3chkFZTI8QSjlmSAQy7i6cPlXQWlzc5wKhj85sJtgClU+KWCaRk5TpUL3JrJ/L1on37nh6Hho0FqJlRCBh5yMjDjsDxnD5pqMYKRgepmQzdBtBhivLKHWD/iwodr/H07gk9nVVJs9kDIeBCO56mTmKL6z9SWmKzi3x2W6XPqGoAn83RE9Nv2fe8xTjeyZkxUQ/up3h9fHC3L45TveIQyoJzDq0ZKzuNJR19NBKH4DPs7I2oouHJ0CW5ghpYMhcQBvyx/ggZ5WOEl+IHRE74wdu9bH8dNUJ13/xUHHKcbCi7D9trpL22adg9wHmQTRr2wDQKqrL0FpwmnSa5s1QH22JZmFj98LH/N2DwUDvFsXnTx+IIkSL5ley41Dws9y9WS17Bctc0rf014/su+B0a6le6WyPCsDjdNGc7Wmyd3QPw0LK7yS/IQqL5wGBeEBPIF6JVnwcuABrBGk05RlmoQk4mxd7S2yFG6rNPL3zVyYXPQ+nyqQnt9UETSnlUx+4f+5X+0V4nI6zhWONo+HUzfq62o7c6wsvLzwtH5nQ8M11zu2RbaHiMEF6V2X2IC8JDQTKpL3A2Nb5JYlJTkh1ik5Kc86xGwFOFogyg/ZKAGascUD1Bkk/EIrGtDtKC8dS0dMVnub2wicnn9ELVHGHg6JEVDImufSPiHLksKGvSp1A11FZagL8l3qPyOmWS3yIZr3Obnt3O03to9JPZTGQqVR12e2LiJqgp4hMTYxZogNU1mgo7iuypo4w9UjZBE6a0kM9pm/0aMrkEe5a9OpbNA+lo8NkpRV1vZdTZCRElz3AAYJanlBDRyryZn4TB
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
