apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCNsfC8oes8oZ2RCbCbZCKHsHvQV56T2ul+VNJyYdvrYwsLczoHSI1IrycWEbFp6Ha+AYHxF8rNzbN4KZ8hkna3dnj8saDwxBYJ5og7QI/rz8PqhLgeA/nxbhlY3TODviFjgg5DEbFaZkQ0T6nOcg3Bkc4gnNu/KrQir0GPJm+nNOatfY3FrZUNrn997V5Kz3hFA9Z6f5YN+IA+eFPvDg0Ma2lBP87ZWoAH5Bds07o6SpcWD21QXFP19Us0+iu3ELiJohLKz5Lv8FSwLlvxkzk8fdOeJ5TO/+rUIZoYpsLnVObm4EqDVdEVv5UuRRYAqU32WfnBxJ83y3hdQfnqekAPt6w4JQJGVTqcXXbrgyZa9idCR1bBY0QFQ3Cs/pDNthxWr1q3RZCMNITw638KBI7oSJz5+lI5mLL0JakE4scRcldiB7v5zTRhWn6egQYNeqGbOBZKWbDOHqS4oIoEpBZqXmMqa9RJgu1Ya3dmnpSs8GOOUbTUhHMdJby1mQ77UB7yK8SklMDT9zPhriTKF3x+7mwcfrD1gTQMEwHx2NDihO1u+u1hcDV1Ny6EHnFhjkintDJRzWQwn+gbVykdiGN1mlWJRY+k2+L+sZCxfUUmrck6x1UmUisDv/QJpZYmYPYNfqWTxai3Z3q/SP9AsTAakeVz8Uce5EQGWgik6Sq6N4fvXIMNwSoJbNMtFXj/z/yTgycEzgK0T5y67OeUYMzoYW7ZSg==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
