apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBsmRtZsZImvVsZHL1Bjp1nD7RdV8VHsdgCsyG5wzeMUYrO6w8ksET1iGXQHmI2a/IxunJIy3PLAFAiIhrY+dkkDC8BSCqDdT3oQdvtg6BWN+sqrmPVG14qCMEx7Y8RXbmr5B1j4Ou5t6qf9+5ypvCJKNcXFNa/d6mTZ8beDdxW0ozNkySxM9EuSfvOmbGhW7BWHDDBUGIiApB0Vsc8B/kuTQ8YR//+IDYbN9f+Vx7SkUoA/VCvF2ocmG9JLmvDXh0uFDmxaTWSHFcMcya58PVVMf9mMjPu+Akkagdy0XF6ilKJrSHHDKLYCCbD0TI9WzMNkrEqrSwmRPDY7EgnWZJ6WsxSNUZ9M9r8aMahvhBoR38TxqCw09ZvyFSR9dG63ljzeHBgJVCnWzQM2vXZ71jkWJvC4iBNiRaZSvhFt6ZJzcr/Rl6OClHlGCC3Ibv6b9I3cMgi/ybk+iCv6OxsKyscf/fq1Z0WDgTKOhobjXLzrIYE3DPczlQ+aYpVfwTqVO5izpqPsG9rsnk254kgMXNIQqt7UTcTYw9t4ahRPQixt+g/xO/keSA/ZhUP4XQ2pZQysSDzKUoaWcTLHntNgAw9gj2NwGbzkMLWoZ+VYQllDLHnBOOM9cOzHP3kvHru3lnzNP7hbvZOBsyMa2oy/57DYrgSdzyWWuVIhCh8gwxkr6mHbft6z+BNA3HYiENZNTg1SPPlXvfEW5HPqf50YY+P7Aa2Qw==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
